name = "portal-testground"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "example"
instances = { min = 1, max = 1, default = 1 }

    [testcases.params]
    greeting = { type = "string", desc = "greeting", default = "Hello" }

[[testcases]]
name = "publish-subscribe"
instances = { min = 2, max = 10, default = 2 }

[[testcases]]
name = "ping-two-way"
instances = { min = 2, max = 2, default = 2 }

    [testcases.params]
    latency = { type = "int", desc = "Latency between peers.", unit = "ms", default = 100 }
    client1 = { type = "string", desc = "name of client i.e. (trin,fluffy,ultralight)", default = "fluffy" }
    client2 = { type = "string", desc = "name of client i.e. (trin,fluffy,ultralight)", default = "ultralight" }

[[testcases]]
name = "ping-one-way"
instances = { min = 2, max = 2, default = 2 }

    [testcases.params]
    latency = { type = "int", desc = "Latency between peers.", unit = "ms", default = 100 }
    client1 = { type = "string", desc = "name of client i.e. (trin,fluffy,ultralight)", default = "trin" }
    client2 = { type = "string", desc = "name of client i.e. (trin,fluffy,ultralight)", default = "fluffy" }

# Add more testcases here...
# [[testcases]]
# name = "another"
# instances = { min = 1, max = 1, default = 1 }
#   [testcase.params]
#   param1 = { type = "int", desc = "an integer", unit = "units", default = 3 }
